"""
Alpha Signal Extractor for Salamander Module

This script extracts specific alpha signals from HDF5 files generated by gen_hl.py
and exports them as CSV files for use in backtesting. It reads the merged data files,
extracts the 'hl' forecast column, and saves it in the format expected by bsim.py.

Usage:
    python gen_alpha.py --start=<start_date> --end=<end_date> --dir=<root_directory>

Arguments:
    --start : Starting date for alpha extraction (format: YYYYMMDD)
              Only files overlapping this date will be processed
              Example: 20130101
    --end   : Ending date for alpha extraction (format: YYYYMMDD)
              Only files overlapping this date will be processed
              Example: 20130630
    --dir   : Root directory containing data/ subfolder
              Default: '.' (current directory)

Input Files:
    data/all/all.<YYYYMMDD>-<YYYYMMDD>.h5
        HDF5 files generated by gen_hl.py containing:
        - MultiIndex: (date, gvkey)
        - Columns: All merged data including 'hl' forecast
        - Key: 'full_df'

Output Files:
    data/hl/alpha.hl.<YYYYMMDD>-<YYYYMMDD>.csv
        CSV files containing:
        - Index: date, gvkey (MultiIndex)
        - Columns: hl (the alpha forecast signal)
        - Format: Standard CSV with headers

File Selection Logic:
    - Scans all files matching data/all/all.*.h5
    - Extracts date range from filename (YYYYMMDD-YYYYMMDD)
    - Includes file if it overlaps with [start, end] date range
    - A file from d1 to d2 is included if: d2 > start AND d1 < end

Process:
    1. Scan data/all/ directory for HDF5 files
    2. Filter files by date range overlap
    3. For each matching file:
       a. Load full_df from HDF5
       b. Extract 'hl' column
       c. Save to CSV in data/hl/ directory
       d. Print extracted signals
    4. Report if no matching files found

Example:
    # Extract alpha signals for first half of 2013
    python gen_alpha.py --start=20130101 --end=20130630 --dir=.

    # Extract signals for full year
    python gen_alpha.py --start=20130101 --end=20131231 --dir=/path/to/project

Output Format:
    The CSV files have this structure:

    date,gvkey,hl
    2013-01-02,001045,0.000234
    2013-01-02,001075,-0.001456
    ...

    These files are loaded by bsim.py when running with --fcast=hl:1:1

Notes:
    - Requires gen_dir.py and gen_hl.py to be run first
    - Only extracts the 'hl' signal; can be modified to extract other columns
    - File date ranges in filenames must match the HDF5 content
    - Prints "insufficient 'all...' files" if no overlapping files found
    - CSV files use MultiIndex (date, gvkey) from the HDF5 DataFrame
"""

import argparse
import os
import glob
import re
import pandas as pd


def main():
    """
    Main function to extract alpha signals from HDF5 files and save as CSV.

    Scans data/all/ directory for HDF5 files, filters by date range,
    extracts the 'hl' alpha signal column, and saves to data/hl/ directory.
    """
    parser = argparse.ArgumentParser()
    parser.add_argument("--start", help="the starting date to generate alpha signals, formatted as 'YYYYMMdd'",
                        type=str)
    parser.add_argument("--end", help="the end date to generate alpha signals, formatted as 'YYYYMMdd'", type=str)
    parser.add_argument("--dir", help="the root directory", type=str, default='.')
    args = parser.parse_args()

    start = args.start
    end = args.end
    dir = args.dir

    found = False
    for ff in sorted(glob.glob(dir + "/data/all/all.*")):
        m = re.match(r".*all\.(\d{8})-(\d{8}).h5", str(ff))
        d1 = m.group(1)
        d2 = m.group(2)
        if d2 <= start or d1 >= end: continue
        print("Loading %s" % ff)
        found = True
        df = pd.read_hdf(ff, key='full_df')
        new = df[['hl']]
        new.to_csv(r"%s/data/hl/alpha.hl.%s-%s.csv" % (dir, d1, d2))
        print(new)
    if not found:
        print("insufficient \"all...\" files")

main()
